### PR TITLE
Add plugin functions

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Create test reports templates for ios projects

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15|1|

For the Pomodoros please check this PR at ios-inventory-agent [#160](https://github.com/flyve-mdm/ios-inventory-agent/pull/160), since this feature was developed simultaneously

### References

Closes #N/A 
Related [#151](https://github.com/flyve-mdm/ios-inventory-agent/issues/151)  
Depends on #N/A

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]

**Comment by Naylin15** [comment]
Update:

The plugin now has the option of using a custom template

**Review by ajsb85 — APPROVED** [review]

**Review by ajsb85 — APPROVED** [review]

**Comment by Naylin15** [comment]
Hi @ajsb85 @Gianfranco97 

I would like to merge this PR to split the CI configuration and tests in other smaller ones (I'll create the issues regarding them) in order to make easier the reviews

Thank you

**Comment by ajsb85** [comment]
I already enabled all GitHub apps to this repository.

**Comment by ajsb85** [comment]
I already added the projects (Website & Plugin) and the milestone of the version 1.0 without due date.

**Pull request merged**
